nfsFileServerIp: 10.0.26.128
cronJobSchedule: '48 * * * *'
volumeSize: 2Gi
sonobuoy:
  runner:
    image: rahulraju/ubuntu-sonobuoy-cli:0.0.1
    cliOptions: "--mode quick"
    resources:
      requests:
        cpu: 500m
        memory: 250Mi
      limits:
        cpu: 1024m
        memory: 500Mi
  grafana:
    enabled: true
    image: grafana/grafana
    resources:
      requests:
        cpu: 500m
        memory: 250Mi
      limits:
        cpu: 1024m
        memory: 500Mi
    service:
      name: sonobuoy-grafana
      type: LoadBalancer
      port: 80
  fileServer:
    image: halverneus/static-file-server:v1.8.4
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 1024m
        memory: 200Mi
    service:
      name: sonobuoy-server
      type: ClusterIP
      port: 80
