{{- $releaseName := .Release.Name -}}
{{- $namespace := .Release.Namespace -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-json-datasource
  namespace: {{ $namespace }}
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: sonobuoy
        type: yesoreyeram-infinity-datasource
        access: proxy
        isDefault: false
        version: 1
        jsonData:
        tlsSkipVerify: false
        readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-sonobuoy-dashboard-provider
  namespace: {{ $namespace }}
data:
  dashboardproviders.yaml: |-
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-sonobuoy-dashboard
  namespace: {{ $namespace }}
data:
  dashboard.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "panels": [
        {
          "id": 2,
          "gridPos": {
            "h": 15,
            "w": 23,
            "x": 0,
            "y": 0
          },
          "datasource": "sonobuoy",
          "fieldConfig": {
            "defaults": {
              "custom": {
                "align": "auto",
                "displayMode": "auto"
              },
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  }
                ]
              },
              "mappings": [
                {
                  "options": {
                    "failed": {
                      "color": "red",
                      "index": 0
                    },
                    "passed": {
                      "color": "green",
                      "index": 1
                    },
                    "skipped": {
                      "color": "super-light-yellow",
                      "index": 2
                    }
                  },
                  "type": "value"
                }
              ],
              "color": {
                "mode": "thresholds"
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Status"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 390
                  },
                  {
                    "id": "custom.displayMode",
                    "value": "color-text"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Testcase"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 1161
                  }
                ]
              }
            ]
          },
          "options": {
            "showHeader": true,
            "sortBy": [
              {
                "desc": false,
                "displayName": "Status"
              }
            ]
          },
          "targets": [
            {
              "columns": [
                {
                  "selector": "status",
                  "text": "Status",
                  "type": "string"
                },
                {
                  "selector": "name",
                  "text": "Testcase",
                  "type": "string"
                }
              ],
              "csv_options": {
                "columns": "",
                "comment": "",
                "delimiter": ",",
                "relax_column_count": false,
                "skip_empty_lines": false,
                "skip_lines_with_error": false
              },
              "data": "",
              "filters": [],
              "format": "table",
              "global_query_id": "",
              "refId": "A",
              "root_selector": "items[0].items[0].items",
              "source": "url",
              "type": "json",
              "url": "http://sonobuoy-server/plugins/e2e/sonobuoy_results.json",
              "url_options": {
                "data": "",
                "method": "GET"
              }
            }
          ],
          "title": "Sonobuoy Results",
          "type": "table"
        }
      ],
      "refresh": "",
      "schemaVersion": 30,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Sonobuoy",
      "uid": "iyWg4NDnz",
      "version": 1
    }
