{{- $releaseName := .Release.Name -}}
{{- $namespace := .Release.Namespace -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $releaseName }}-pv
  namespace: {{ $namespace }}
spec:
  capacity:
    storage: {{ .Values.volumeSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: {{ .Values.nfsFileServerIp }}
