{{- $releaseName := .Release.Name -}}
{{- $namespace := .Release.Namespace -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $releaseName }}-shared-volume
  namespace: {{ $namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.volumeSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
