apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sonobuoy
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sonobuoy
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sonobuoy
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sonobuoy
  type: LoadBalancer
