apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: sonobuoy
spec:
  serviceAccountName: {{ .Release.Name }}-sa
  automountServiceAccountToken: true
  volumes:
    - name: sonobuoy
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-shared-volume
    - name: grafana-datasource-config
      configMap:
        name: json-datasource
    - name: grafana-dashboard-config
      configMap:
        name: sonobuoy-dashboard
    - name: sonobuoy-dashboard-provider-config
      configMap:
        name: sonobuoy-dashboard-provider
  containers:
  - image: halverneus/static-file-server
    name: server
    resources: {}
    volumeMounts:
    - mountPath: /web
      name: sonobuoy
  - image: grafana/grafana
    name: grafana
    resources: {}
    env:
    - name: GF_INSTALL_PLUGINS
      value: yesoreyeram-infinity-datasource,marcusolsson-json-datasource
    volumeMounts:
      - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
        name: grafana-datasource-config
        subPath: datasources.yaml
      - mountPath: /var/lib/grafana/dashboards/default/
        name: grafana-dashboard-config
      - mountPath: /etc/grafana/provisioning/dashboards/dashboardproviders.yaml
        name: sonobuoy-dashboard-provider-config
        subPath: dashboardproviders.yaml
  restartPolicy: Never
