{{- $releaseName := .Release.Name -}}
{{- $namespace := .Release.Namespace -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $releaseName }}-runner-cron
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $releaseName }}
    helm.sh/chart: {{ $chartName }}
    helm.sh/chart-version: {{ $chartVersion }}
    app: sonobuoy
spec:
  jobTemplate:
    metadata:
      name: {{ $releaseName }}-runner
      labels:
        app.kubernetes.io/name: {{ $releaseName }}
        helm.sh/chart: {{ $chartName }}
        helm.sh/chart-version: {{ $chartVersion }}
        app: sonobuoy
    spec:
      template:
        metadata:
          name: {{ $releaseName }}
          labels:
            app.kubernetes.io/name: {{ $releaseName }}
            helm.sh/chart: {{ $chartName }}
            helm.sh/chart-version: {{ $chartVersion }}
            app: sonobuoy
        spec:
          serviceAccountName: {{ $releaseName }}-sa
          automountServiceAccountToken: true
          volumes:
            - name: sonobuoy
              persistentVolumeClaim:
                claimName: {{ $releaseName }}-shared-volume
          initContainers:
            - image: {{ .Values.sonobuoy.runner.image }}
              name: runner
              resources:
                requests:
                  cpu: {{ .Values.sonobuoy.runner.resources.requests.cpu }}
                  memory: {{ .Values.sonobuoy.runner.resources.requests.memory }}
                limits:
                  cpu: {{ .Values.sonobuoy.runner.resources.limits.cpu }}
                  memory: {{ .Values.sonobuoy.runner.resources.limits.memory }}
              command:
                - "sh"
                - "-c"
                - "sonobuoy run {{ .Values.sonobuoy.runner.cliOptions }} --wait --wait-output progress && cd /sonobuoy && sonobuoy retrieve -f=results.tar.gz && sleep 30 && tar -xzf results.tar.gz && sonobuoy delete --wait"
              volumeMounts:
                - mountPath: /sonobuoy
                  name: sonobuoy
          containers:
            - image: simplealpine/yaml2json
              name: fileconvertor
              resources: {}
              command:
                - sh
                - "-c"
                - "yaml2json /sonobuoy/plugins/e2e/sonobuoy_results.yaml > /sonobuoy/plugins/e2e/sonobuoy_results.json"
              volumeMounts:
                - mountPath: /sonobuoy
                  name: sonobuoy
          restartPolicy: OnFailure
  schedule: {{ .Values.cronJobSchedule }}
